# Generated by Django 6.0.3 on 2026-04-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('matricule', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(choices=[('actif', 'Àctif'), ('inactif', 'Inactif'), ('en_probation', 'En probation'), ('default', '')], default='default', max_length=20)),
                ('cotisation', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
