# Generated by Django 6.0.5 on 2026-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_delete_membre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='id',
        ),
        migrations.RemoveField(
            model_name='members',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='members',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='members',
            name='member_id',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='members',
            name='family_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.CharField(choices=[('actif', 'Àctif'), ('inactif', 'Inactif'), ('en_probation', 'En probation')], default='inactif', max_length=15),
        ),
    ]
