# Generated by Django 6.0.5 on 2026-05-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_members_id_remove_members_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_probation', 'En probation')], default='', max_length=15),
        ),
    ]
