# Generated by Django 6.0.5 on 2026-05-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_members_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='password',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_probation', 'En probation')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_probation', 'En probation')], default='inactif', max_length=15),
        ),
    ]
